---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@1
jobs:
  test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 2.3.11
      rails_version:
        type: string
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - run:
          name: Install the FITS
          command: |
            mkdir ~/fits
            wget "https://github.com/harvard-lts/fits/releases/download/1.4.1/fits-1.4.1.zip"
            unzip -d ~/fits/ "fits-1.4.1.zip"
            chmod a+x ~/fits/fits.sh
            ln -s ~/fits/fits.sh ~/fits/fits
            rm "fits-1.4.1.zip"
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-file_characterization
      - run:
          name: Update the PATH env. variable
          command: |
            echo "export PATH=$HOME/fits:$PATH" >> $BASH_ENV
            source $BASH_ENV
      - samvera/rubocop
      - samvera/parallel_rspec

workflows:
  version: 2
  ci:
    jobs:
      - test:
          name: bundle_ruby3-3_rails7-2
          ruby_version: 3.3.5
          rails_version: 7.2.1
      - test:
          name: bundle_ruby3-3_rails7-1
          ruby_version: 3.3.5
          rails_version: 7.1.4
      - test:
          name: bundle_ruby3-3_rails7-0
          ruby_version: 3.3.5
          rails_version: 7.0.8.4
      - test:
          name: bundle_ruby3-2_rails7-2
          ruby_version: 3.2.5
          rails_version: 7.2.1
      - test:
          name: bundle_ruby3-2_rails7-1
          ruby_version: 3.2.5
          rails_version: 7.1.4
      - test:
          name: bundle_ruby3-2_rails7-0
          ruby_version: 3.2.5
          rails_version: 7.0.8.4
      - test:
          name: bundle_ruby3-1_rails7-2
          ruby_version: 3.1.6
          rails_version: 7.2.1
      - test:
          name: bundle_ruby3-1_rails7-1
          ruby_version: 3.1.6
          rails_version: 7.1.4
      - test:
          name: bundle_ruby3-1_rails7-0
          ruby_version: 3.1.6
          rails_version: 7.0.8.4

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test:
          name: bundle_ruby3-3_rails7-2
          ruby_version: 3.3.5
          rails_version: 7.2.1
      - test:
          name: bundle_ruby3-3_rails7-1
          ruby_version: 3.3.5
          rails_version: 7.1.4
      - test:
          name: bundle_ruby3-3_rails7-0
          ruby_version: 3.3.5
          rails_version: 7.0.8.4
      - test:
          name: bundle_ruby3-2_rails7-2
          ruby_version: 3.2.5
          rails_version: 7.2.1
      - test:
          name: bundle_ruby3-2_rails7-1
          ruby_version: 3.2.5
          rails_version: 7.1.4
      - test:
          name: bundle_ruby3-2_rails7-0
          ruby_version: 3.2.5
          rails_version: 7.0.8.4
      - test:
          name: bundle_ruby3-1_rails7-2
          ruby_version: 3.1.6
          rails_version: 7.2.1
      - test:
          name: bundle_ruby3-1_rails7-1
          ruby_version: 3.1.6
          rails_version: 7.1.4
      - test:
          name: bundle_ruby3-1_rails7-0
          ruby_version: 3.1.6
          rails_version: 7.0.8.4
