---
version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  test:
    parameters:
      ruby_version:
        type: string
      bundler_version:
        type: string
        default: 1.17.3
      rails_version:
        type: string
    executor:
      name: 'samvera/ruby_fcrepo_solr'
      ruby_version: << parameters.ruby_version >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - run:
          name: Install the FITS
          command: |
            mkdir ~/fits
            wget "https://github.com/harvard-lts/fits/releases/download/1.4.1/fits-1.4.1.zip"
            unzip -d ~/fits/ "fits-1.4.1.zip"
            chmod a+x ~/fits/fits.sh
            ln -s ~/fits/fits.sh ~/fits/fits
            rm "fits-1.4.1.zip"
      - samvera/cached_checkout
      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: hydra-file_characterization
      - run:
          name: Update the PATH env. variable
          command: |
            echo "export PATH=$HOME/fits:$PATH" >> $BASH_ENV
            source $BASH_ENV
      - samvera/rubocop
      - samvera/parallel_rspec

workflows:
  version: 2
  ci:
    jobs:
      - test:
          name: ruby2-7_rails6-0
          ruby_version: 2.7.0
          rails_version: 6.0.2
      - test:
          name: ruby2-6_rails6-0
          ruby_version: 2.6.5
          rails_version: 6.0.2
      - test:
          name: ruby2-5_rails6-0
          ruby_version: 2.5.7
          rails_version: 6.0.2
      - test:
          name: ruby2-7_rails5-2
          ruby_version: 2.7.0
          rails_version: 5.2.4
      - test:
          name: ruby2-6_rails5-2
          ruby_version: 2.6.5
          rails_version: 5.2.4
      - test:
          name: ruby2-5_rails5-2
          ruby_version: 2.5.7
          rails_version: 5.2.4
      - test:
          name: ruby2-4_rails5-2
          ruby_version: 2.4.9
          rails_version: 5.2.4
      - test:
          name: ruby2-7_rails5-1
          ruby_version: 2.7.0
          rails_version: 5.1.7
      - test:
          name: ruby2-6_rails5-1
          ruby_version: 2.6.5
          rails_version: 5.1.7
      - test:
          name: ruby2-5_rails5-1
          ruby_version: 2.5.7
          rails_version: 5.1.7
      - test:
          name: ruby2-4_rails5-1
          ruby_version: 2.4.9
          rails_version: 5.1.7
